from . import discount_code
from . import pos_config
from . import pos_order
from . import pos_nc_rejection
from . import pos_hacienda_rejection_reason
from . import pos_order_line
from . import pos_payment_method
from . import pos_session
from . import reference_code
from . import res_config_settings