# -*- coding: utf-8 -*-

{
    "name": "Ticofac - Localización Costa Rica",
    "summary": "Facturación electrónica y localización costarricense unificada",
    "version": "18.0.1.0.0",
    "category": "Accounting/Localizations",
    "author": (
        "Tecno Servicios Artavia; basado en contribuciones de "
        "OpenCR, OdooFeCR, Singulary, SNG y CYSFuturo"
    ),
    "website": "https://www.ticofac.com",
    "license": "AGPL-3",
    "depends": [
        "base",
        "base_setup",
        "contacts",
        "account",
        "mail",
        "product",
        "uom",
        "sale_management",
        "sales_team",
        "sale_stock",
        "stock",
        "point_of_sale",
        "l10n_cr",
    ],
    "external_dependencies": {
        "python": [
            "cryptography",
            "phonenumbers",
            "jsonschema",
            "pandas",
            "openpyxl",
            "zeep",
        ],
    },
    "data": [
        "components/country_codes/data/res_country_state.xml",
        "components/country_codes/data/res.country.county.csv",
        "components/country_codes/data/res.country.district.csv",
        "components/country_codes/data/res.country.neighborhood.csv",
        "components/country_codes/security/ir.model.access.csv",
        "components/country_codes/views/res_country_county_views.xml",
        "components/country_codes/views/res_country_district_views.xml",
        "components/country_codes/views/res_country_neighborhood_views.xml",
        "components/country_codes/views/res_company_views.xml",
        "components/country_codes/views/res_partner_views.xml",
        "components/hacienda_query/views/res_config_settings_views.xml",
        "components/hacienda_query/data/res_config_settings.xml",
        "components/currency_adapter/data/currency_data.xml",
        "components/currency_adapter/views/res_currency_view.xml",
        "components/currency_adapter/views/res_currency_rate_view.xml",
        "components/currency_adapter/views/res_config_settings_views.xml",
        "components/electronic_invoice/data/account_tax_group_data.xml",
        "components/electronic_invoice/data/account_tax_data.xml",
        "components/electronic_invoice/data/aut_ex_data.xml",
        "components/electronic_invoice/data/code_type_product_data.xml",
        "components/electronic_invoice/data/identification_type_data.xml",
        "components/electronic_invoice/data/ir_cron_data.xml",
        "components/electronic_invoice/data/mail_template_data.xml",
        "components/electronic_invoice/data/payment_methods_data.xml",
        "components/electronic_invoice/data/reference_code_data.xml",
        "components/electronic_invoice/data/reference_document_data.xml",
        "components/electronic_invoice/data/sale_conditions_data.xml",
        "components/electronic_invoice/data/product_category_data.xml",
        "components/electronic_invoice/data/product_data.xml",
        "components/electronic_invoice/data/uom_data.xml",
        "components/electronic_invoice/data/economic.activity.csv",
        "components/electronic_invoice/data/sequence.xml",
        "components/electronic_invoice/data/res.currency.xml",
        "components/electronic_invoice/data/decimal_precision.xml",
        "components/electronic_invoice/data/discount_code_data.xml",
        "components/electronic_invoice/views/uom_views.xml",
        "components/electronic_invoice/views/account_move_views.xml",
        "components/electronic_invoice/views/account_journal_views.xml",
        "components/electronic_invoice/views/account_payment_views.xml",
        "components/electronic_invoice/views/code_type_product_views.xml",
        "components/electronic_invoice/views/identification_type_views.xml",
        "components/electronic_invoice/views/product_views.xml",
        "components/electronic_invoice/views/reference_document_views.xml",
        "components/electronic_invoice/views/res_partner_views.xml",
        "components/electronic_invoice/views/resolution_views.xml",
        "components/electronic_invoice/views/sale_condition_views.xml",
        "components/electronic_invoice/views/account_tax_views.xml",
        "components/electronic_invoice/views/economic_activity_views.xml",
        "components/electronic_invoice/views/discount_code_views.xml",
        "components/electronic_invoice/views/account_move_reversal_views.xml",
        "components/electronic_invoice/views/account_payment_register_views.xml",
        "components/electronic_invoice/views/report_invoice.xml",
        "components/electronic_invoice/views/account_portal_templates.xml",
        "components/electronic_invoice/views/web_external_layout_striped.xml",
        "components/electronic_invoice/security/ir.model.access.csv",
        "components/cabys/views/cabys_producto_views.xml",
        "components/cabys/data/pharmaceutical_forms_data.xml",
        "components/cabys/views/pharmaceutical_form_views.xml",
        "components/cabys/views/cabys_views.xml",
        "components/cabys/views/product_product_views.xml",
        "components/cabys/views/product_template_views.xml",
        "components/cabys/views/product_category_views.xml",
        "components/cabys/wizard/cabys_catalog_import_wizard.xml",
        "components/cabys/security/ir.model.access.csv",
        "components/cabys_sac/data/ir_config_parameter.xml",
        "components/cabys_sac/security/ir.model.access.csv",
        "components/cabys_sac/views/sac_equivalence_views.xml",
        "components/cabys_sac/wizard/sac_import_wizard.xml",
        "components/cabys_sac/views/product_template_views.xml",
        "components/cabys_sac/views/res_config_settings_stock_views.xml",
        "components/vendor_bills/views/account_move.xml",
        "components/journal_fields/views/account_journal_view.xml",
        "components/journal_fields/views/account_move_view.xml",
        "components/invoice_qweb/data/report_paperformat_data.xml",
        "components/invoice_qweb/views/account_move_views.xml",
        "components/invoice_qweb/views/report_sales_invoice_qweb.xml",
        "components/economic_activity_cron/data/ir_cron.xml",
        "components/pos/data/res.partner.csv",
        "components/pos/views/res_config_settings_view.xml",
        "components/pos/views/pos_payment_method_form.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "l10n_cr_ticofac/static/src/scss/ticofac_backend.scss",
        ],
        "point_of_sale._assets_pos": [
            "l10n_cr_ticofac/static/src/pos/js/models.js",
            "l10n_cr_ticofac/static/src/pos/js/pos_order_line.js",
            "l10n_cr_ticofac/static/src/pos/js/discount_code_popup.js",
            "l10n_cr_ticofac/static/src/pos/js/control_buttons.js",
            "l10n_cr_ticofac/static/src/pos/js/payment_screen.js",
            "l10n_cr_ticofac/static/src/pos/js/ticket_screen.js",
            "l10n_cr_ticofac/static/src/pos/scss/ticket_screen.scss",
            "l10n_cr_ticofac/static/src/pos/js/credit_note_popup.js",
            "l10n_cr_ticofac/static/src/pos/xml/custom_orderReceipt.xml",
            "l10n_cr_ticofac/static/src/pos/xml/discount_code_popup.xml",
            "l10n_cr_ticofac/static/src/pos/xml/control_buttons.xml",
            "l10n_cr_ticofac/static/src/pos/xml/credit_note_popup.xml",
        ],
    },
    # Se habilitará después de integrar y validar todos los componentes.
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
}
